services:
  postgres:
    image: postgres:latest
    container_name: routescan_postgres
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: c_chain
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d c_chain"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
